"""Export a compact exception-register preview for GitHub reviewers."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

DEFAULT_INPUT = Path("outputs/exception_register.csv")
DEFAULT_OUTPUT = Path("docs/exception-register-preview.md")
PREVIEW_ROW_LIMIT = 12
SEVERITY_ORDER = {"High": 0, "Medium": 1, "Low": 2}
PREVIEW_COLUMNS = [
    "record_id",
    "rule_id",
    "severity",
    "field",
    "issue",
    "recommended_action",
]


def _markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def _sort_key(row: dict[str, str]) -> tuple[int, str, str]:
    return (
        SEVERITY_ORDER.get(row["severity"], 99),
        row["rule_id"],
        row["record_id"],
    )


def _build_markdown(rows: list[dict[str, str]], source: Path) -> str:
    sorted_rows = sorted(rows, key=_sort_key)
    preview_rows = sorted_rows[:PREVIEW_ROW_LIMIT]
    hidden_count = max(len(sorted_rows) - len(preview_rows), 0)

    lines = [
        "# Exception Register Preview",
        "",
        f"This preview is generated by `scripts/export_exception_preview.py` from `{source}`.",
        "",
        f"Showing {len(preview_rows)} of {len(sorted_rows)} exceptions, sorted by "
        "severity, rule, and record.",
        "",
        "| Record | Rule | Severity | Field | Issue | Recommended action |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for row in preview_rows:
        lines.append(
            "| " + " | ".join(_markdown_escape(row[column]) for column in PREVIEW_COLUMNS) + " |"
        )

    if hidden_count:
        lines.extend(
            [
                "",
                f"{hidden_count} additional exceptions are available in `{source}`.",
            ]
        )

    lines.extend(
        [
            "",
            "This file is a reviewer convenience only. The CSV remains the "
            "authoritative exception register.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default=DEFAULT_INPUT, type=Path)
    parser.add_argument("--output", default=DEFAULT_OUTPUT, type=Path)
    args = parser.parse_args()

    if not args.input.exists():
        print(f"ERROR: missing exception register: {args.input}")
        return 1

    rows = _read_rows(args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(_build_markdown(rows, args.input), encoding="utf-8")
    print(f"Wrote {args.output} from {args.input}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
